#!/usr/bin/env python3
"""Real-world display names for the 17x14 national War Factory roster.

Object names, models, weapons, and balance are not changed here.
Keys are existing Object names. Values are (DisplayName, Tooltip).
"""

from __future__ import annotations

# role order: mbt, heavy, recon, ifv, apc, shorad, sam, radar, mlrs, ballistic, spa, at, eng, special
NAMES: dict[str, tuple[str, str]] = {
    # Japan
    "JapanTankType10": ("Type 10", "JGSDF Type 10 main battle tank"),
    "JapanTankType90": ("Type 90", "JGSDF Type 90 main battle tank"),
    "JapanVehicleType16": ("Type 16 MCV", "JGSDF Type 16 maneuver combat vehicle"),
    "JapanVehicleType89": ("Type 89 IFV", "JGSDF Type 89 infantry fighting vehicle"),
    "JapanVehicleType96": ("Type 96 WAPC", "JGSDF Type 96 wheeled APC"),
    "JapanVehicleType87": ("Type 87 SPAAG", "JGSDF Type 87 self-propelled anti-aircraft gun"),
    "JapanVehicleChuSAM": ("Type 03 Chu-SAM", "JGSDF Type 03 Chu-SAM medium-range SAM"),
    "JapanVehicleRadar": ("J/TPS-P18", "JGSDF J/TPS-P18 air-search radar"),
    "JapanVehicleM270": ("M270 MLRS", "JGSDF licensed M270 rocket launcher"),
    "JapanVehicleType12": ("Type 12 SSM", "JGSDF Type 12 surface-to-ship missile"),
    "JapanVehicleType99": ("Type 99 SPH", "JGSDF Type 99 self-propelled howitzer"),
    "JapanVehicleType16AT": ("Type 96 MPMS", "JGSDF Type 96 multi-purpose missile system"),
    "JapanVehicleType11ARV": ("Type 11 ARV", "JGSDF Type 11 armored recovery vehicle"),
    "JapanVehicleType12Btry": ("Type 88 SSM", "JGSDF Type 88 surface-to-ship missile"),
    # South Korea
    "SouthKoreaTankK1A2": ("K2 Black Panther", "ROK Army K2 Black Panther main battle tank"),
    "SouthKoreaTankK1A1": ("K1A2", "ROK Army K1A2 main battle tank"),
    "SouthKoreaVehicleK200": ("K806 White Tiger", "ROK Army K806 White Tiger recon vehicle"),
    "SouthKoreaVehicleK21": ("K21 IFV", "ROK Army K21 infantry fighting vehicle"),
    "SouthKoreaVehicleK200APC": ("K200A1", "ROK Army K200A1 armored personnel carrier"),
    "SouthKoreaVehicleK30": ("K30 Biho", "ROK Army K30 Biho self-propelled AA"),
    "SouthKoreaVehicleCheongung": ("KM-SAM", "ROK Army KM-SAM Cheongung"),
    "SouthKoreaVehicleRadar": ("TPS-830K", "ROK Army TPS-830K air-defense radar"),
    "SouthKoreaVehicleChunmoo": ("K239 Chunmoo", "ROK Army K239 Chunmoo MLRS"),
    "SouthKoreaVehicleHyunmoo": ("Hyunmoo Missile", "ROK Army Hyunmoo-2 ballistic missile TEL"),
    "SouthKoreaVehicleK9": ("K9 Thunder", "ROK Army K9 Thunder self-propelled howitzer"),
    "SouthKoreaVehicleK21AT": ("AT-1K Raybolt", "ROK Army AT-1K Raybolt anti-tank vehicle"),
    "SouthKoreaVehicleK288": ("K288 ARV", "ROK Army K288 recovery vehicle"),
    "SouthKoreaVehicleHyunmoo2B": ("Hyunmoo-3", "ROK Army Hyunmoo-3 cruise-missile TEL"),
    # Germany
    "GermanyTankLeopard2A7": ("Leopard 2A7", "Bundeswehr Leopard 2A7 main battle tank"),
    "GermanyTankLeopard2A6": ("Leopard 2A6", "Bundeswehr Leopard 2A6 main battle tank"),
    "GermanyVehicleFennek": ("Fennek", "Bundeswehr Fennek recon vehicle"),
    "GermanyVehiclePuma": ("Puma", "Bundeswehr Puma infantry fighting vehicle"),
    "GermanyVehicleBoxer": ("Boxer", "Bundeswehr Boxer armored personnel carrier"),
    "GermanyVehicleGepard": ("Gepard", "Bundeswehr Gepard self-propelled AA"),
    "GermanyVehicleIRIST": ("IRIS-T", "Bundeswehr IRIS-T SLM"),
    "GermanyVehicleTRML": ("TRML-4D", "Bundeswehr TRML-4D air-defense radar"),
    "GermanyVehicleMARS": ("MARS II", "Bundeswehr MARS II / M270 MLRS"),
    "GermanyVehicleTaurusTEL": ("Taurus", "Taurus KEPD 350 cruise-missile launcher"),
    "GermanyVehiclePzH2000": ("PzH 2000", "Bundeswehr PzH 2000 self-propelled howitzer"),
    "GermanyVehicleWieselAT": ("Wiesel TOW", "Wiesel 1 TOW anti-tank vehicle"),
    "GermanyVehicleBuffel": ("BPz3 Buffel", "Bundeswehr BPz3 Buffel recovery vehicle"),
    "GermanyVehicleBoxerAA": ("Boxer Skyranger", "Boxer Skyranger 30 air-defense vehicle"),
    # France
    "FranceTankLeclerc": ("Leclerc", "Armee de Terre Leclerc main battle tank"),
    "FranceTankAMX30": ("AMX-30B2", "AMX-30B2 Brenus heavy tank"),
    "FranceVehicleAMX10RC": ("AMX-10RC", "AMX-10RC armored recon vehicle"),
    "FranceVehicleVBCI": ("VBCI", "VBCI infantry fighting vehicle"),
    "FranceVehicleVAB": ("VBMR Griffon", "VBMR Griffon armored personnel carrier"),
    "FranceVehicleMistral": ("Mistral", "Mistral short-range air-defense vehicle"),
    "FranceVehicleSAMPT": ("SAMP/T", "SAMP/T Mamba air-defense system"),
    "FranceVehicleGM200": ("Ground Master 200", "Thales Ground Master 200 radar"),
    "FranceVehicleLRU": ("M270", "French M270 LRU rocket launcher"),
    "FranceVehicleSCALPTEL": ("SCALP", "SCALP / MdCN cruise-missile launcher"),
    "FranceVehicleCaesar": ("Caesar", "CAESAR 155mm self-propelled howitzer"),
    "FranceVehicleVABHOT": ("VAB HOT", "VAB HOT anti-tank vehicle"),
    "FranceVehicleDNG": ("Leclerc DNG", "Leclerc DNG recovery vehicle"),
    "FranceVehicleJaguar": ("EBRC Jaguar", "EBRC Jaguar combat recon vehicle"),
    # Britain
    "BritainTankChallenger2": ("Challenger 2", "British Army Challenger 2 main battle tank"),
    "BritainTankChallenger2TES": ("Challenger 2 TES", "Challenger 2 TES heavy urban tank"),
    "BritainVehicleAjax": ("Ajax", "Ajax armored recon vehicle"),
    "BritainVehicleWarrior": ("Warrior", "FV510 Warrior infantry fighting vehicle"),
    "BritainVehicleMastiff": ("Mastiff", "Mastiff protected patrol vehicle / APC"),
    "BritainVehicleStormer": ("Stormer HVM", "Stormer HVM Starstreak SHORAD"),
    "BritainVehicleSkySabre": ("Sky Sabre", "Sky Sabre air-defense system"),
    "BritainVehicleGiraffe": ("Giraffe", "Saab Giraffe radar for Sky Sabre"),
    "BritainVehicleGMLRS": ("M270 GMLRS", "British M270 GMLRS rocket launcher"),
    "BritainVehicleStormShadowTEL": ("Storm Shadow", "Storm Shadow cruise-missile launcher"),
    "BritainVehicleAS90": ("AS90", "AS90 self-propelled gun"),
    "BritainVehicleStriker": ("FV102 Striker", "FV102 Striker anti-tank vehicle"),
    "BritainVehicleCRARRV": ("CRARRV", "Challenger armored repair and recovery vehicle"),
    "BritainVehicleTrojan": ("Trojan AVRE", "Trojan combat engineer vehicle"),
    # Italy
    "ItalyTankAriete": ("C2 Ariete", "Esercito C2 Ariete main battle tank"),
    "ItalyTankArieteC1": ("C1 Ariete", "Esercito C1 Ariete heavy tank"),
    "ItalyVehicleCentauro": ("B1 Centauro", "B1 Centauro wheeled tank destroyer"),
    "ItalyVehicleDardo": ("Dardo", "Dardo infantry fighting vehicle"),
    "ItalyVehicleVBM": ("Freccia", "VBM Freccia armored personnel carrier"),
    "ItalyVehicleSIDAM": ("SIDAM 25", "SIDAM 25 self-propelled AA"),
    "ItalyVehicleSAMPT": ("SAMP/T", "Italian SAMP/T air-defense system"),
    "ItalyVehicleRAT31": ("RAT-31DL", "RAT-31DL air-defense radar"),
    "ItalyVehicleM270": ("M270 MLRS", "Italian M270 rocket launcher"),
    "ItalyVehicleStormShadowTEL": ("Storm Shadow", "Storm Shadow cruise-missile launcher"),
    "ItalyVehiclePzH2000": ("PzH 2000", "Italian PzH 2000 self-propelled howitzer"),
    "ItalyVehicleCentauroAT": ("Centauro 105", "B1 Centauro 105mm anti-tank vehicle"),
    "ItalyVehicleARV": ("Ariete ARV", "Ariete armored recovery vehicle"),
    "ItalyVehicleCentauro2": ("Centauro II", "Centauro II 120mm wheeled tank destroyer"),
    # Turkey
    "TurkeyTankLeopard2A4": ("Leopard 2A4", "TSK Leopard 2A4 main battle tank"),
    "TurkeyTankM60T": ("M60T Sabra", "TSK M60T Sabra heavy tank"),
    "TurkeyVehicleKaplan": ("Kaplan-20", "Kaplan-20 recon / light tracked vehicle"),
    "TurkeyVehicleACV15": ("Tulpar IFV", "Tulpar infantry fighting vehicle"),
    "TurkeyVehicleKirpi": ("Kirpi", "BMC Kirpi armored personnel carrier"),
    "TurkeyVehicleKorkut": ("Korkut", "Korkut self-propelled AA"),
    "TurkeyVehicleHisar": ("Hisar", "Hisar-O medium-range SAM"),
    "TurkeyVehicleKalkan": ("Kalkan", "Kalkan air-defense radar"),
    "TurkeyVehicleKasirga": ("T-300 Kasirga", "T-300 Kasirga multiple rocket launcher"),
    "TurkeyVehicleBora": ("Bora Missile", "Bora / Khan ballistic missile TEL"),
    "TurkeyVehicleFirtina": ("T-155 Firtina", "T-155 Firtina self-propelled howitzer"),
    "TurkeyVehicleACVTOW": ("ACV-15 TOW", "ACV-15 TOW anti-tank vehicle"),
    "TurkeyVehicleM88": ("M88 ARV", "M88 armored recovery vehicle"),
    "TurkeyVehicleAltay": ("Altay", "Altay indigenous main battle tank"),
    # Ukraine
    "UkraineTankT84": ("T-84", "Ukrainian T-84 Oplot main battle tank"),
    "UkraineTankT72AMT": ("T-72AMT", "Ukrainian T-72AMT heavy tank"),
    "UkraineVehicleBRDM": ("BRDM-2", "BRDM-2 armored recon vehicle"),
    "UkraineVehicleBMP2": ("BMP-2", "BMP-2 infantry fighting vehicle"),
    "UkraineVehicleBTR4": ("BTR-4", "BTR-4 Bucephalus armored personnel carrier"),
    "UkraineVehicleGepard": ("Gepard", "Flakpanzer Gepard self-propelled AA"),
    "UkraineVehicleBuk": ("Buk-M1", "Buk-M1 medium-range SAM"),
    "UkraineVehicleP18": ("35D6", "35D6 / ST-68 air-search radar"),
    "UkraineVehicleHIMARS": ("HIMARS", "M142 HIMARS rocket launcher"),
    "UkraineVehicleHrim2": ("Hrim-2", "Hrim-2 ballistic missile TEL"),
    "UkraineVehicleBohdana": ("2S22 Bohdana", "2S22 Bohdana self-propelled howitzer"),
    "UkraineVehicleStugna": ("Stugna-P", "Stugna-P anti-tank missile vehicle"),
    "UkraineVehicleBREM": ("BREM-1", "BREM-1 armored recovery vehicle"),
    "UkraineTankT64BV": ("Neptune", "R-360 Neptune coastal missile launcher"),
    # Sweden
    "SwedenTankStrv122": ("Strv 122", "Stridsvagn 122 main battle tank"),
    "SwedenTankStrv121": ("Strv 121", "Stridsvagn 121 heavy tank"),
    "SwedenVehicleCV90R": ("CV90 Recce", "CV90 recce vehicle"),
    "SwedenVehicleCV90": ("CV90", "Strf 90 infantry fighting vehicle"),
    "SwedenVehiclePatgb203": ("Patgb 203", "Patgb 203 armored personnel carrier"),
    "SwedenVehicleLvkv90": ("Lvkv 90", "Lvkv 90 air-defense CV90"),
    "SwedenVehicleIRIST": ("IRIS-T SLS", "IRIS-T SLS short-range SAM"),
    "SwedenVehicleGiraffe": ("Giraffe AMB", "Giraffe AMB air-defense radar"),
    "SwedenVehiclePULS": ("PULS", "PULS multiple rocket launcher"),
    "SwedenVehicleRBS15": ("RBS-15", "RBS-15 coastal missile launcher"),
    "SwedenVehicleArcher": ("Archer", "Archer FH77BW self-propelled howitzer"),
    "SwedenVehicleCV90AT": ("CV90120", "CV90120 anti-tank vehicle"),
    "SwedenVehicleBgbv120": ("Bgbv 120", "Bgbv 120 recovery vehicle"),
    "SwedenTankStrv122B": ("Strv 122B+", "Stridsvagn 122B+ special tank"),
    # India
    "IndiaTankT90S": ("T-90 Bhishma", "Indian T-90S Bhishma main battle tank"),
    "IndiaTankT72Ajeya": ("T-72 Ajeya", "T-72M1 Ajeya heavy tank"),
    "IndiaVehicleNAMICA": ("NAMICA", "Nag missile carrier recon vehicle"),
    "IndiaVehicleBMP2": ("BMP-2", "BMP-2 Sarath infantry fighting vehicle"),
    "IndiaVehicleKestrel": ("Tata Kestrel", "Tata Kestrel wheeled APC"),
    "IndiaVehicleTunguska": ("2S6 Tunguska", "2S6 Tunguska self-propelled AA"),
    "IndiaVehicleAkash": ("Akash", "Akash medium-range SAM"),
    "IndiaVehicleRajendra": ("Rajendra", "Rajendra 3D air-defense radar"),
    "IndiaVehiclePinaka": ("Pinaka", "Pinaka multiple rocket launcher"),
    "IndiaVehiclePrahaar": ("Prahaar", "Prahaar tactical ballistic missile TEL"),
    "IndiaVehicleK9Vajra": ("K9 Vajra", "K9 Vajra-T self-propelled howitzer"),
    "IndiaVehicleNag": ("Nag", "Nag anti-tank missile vehicle"),
    "IndiaVehicleVT72B": ("VT-72B", "VT-72B armored recovery vehicle"),
    "IndiaTankArjun": ("Arjun", "Arjun Mk1A indigenous main battle tank"),
    # Pakistan
    "PakistanTankAlKhalid": ("Al-Khalid", "Al-Khalid main battle tank"),
    "PakistanTankAlZarrar": ("Al-Zarrar", "Al-Zarrar heavy tank"),
    "PakistanVehicleMohafiz": ("Mohafiz", "Mohafiz scout vehicle"),
    "PakistanVehicleTalhaIFV": ("Saad", "Saad infantry fighting vehicle"),
    "PakistanVehicleTalhaAPC": ("Talha", "Talha armored personnel carrier"),
    "PakistanVehicleLY80": ("LY-80", "LY-80 / HQ-16 short-range SAM"),
    "PakistanVehicleHQ9P": ("HQ-9/P", "HQ-9/P air-defense system"),
    "PakistanVehicleRadar": ("IBIS-150", "IBIS-150 air-defense radar"),
    "PakistanVehicleA100": ("A-100", "A-100 multiple rocket launcher"),
    "PakistanVehicleShaheen": ("Shaheen-II", "Shaheen-II ballistic missile TEL"),
    "PakistanVehicleM109": ("M109A2", "M109A2 self-propelled howitzer"),
    "PakistanVehicleBaktar": ("Baktar-Shikan", "Baktar-Shikan anti-tank vehicle"),
    "PakistanVehicleARV": ("Al-Hadeed", "Al-Hadeed armored recovery vehicle"),
    "PakistanVehicleNasr": ("Nasr", "Nasr short-range ballistic missile TEL"),
    # Saudi Arabia
    "SaudiArabiaTankM1A2": ("M1A2S Abrams", "Royal Saudi M1A2S Abrams main battle tank"),
    "SaudiArabiaTankM1A2S": ("M1A2 Abrams", "Royal Saudi M1A2 Abrams heavy tank"),
    "SaudiArabiaVehicleLAV25": ("LAV-25", "LAV-25 recon vehicle"),
    "SaudiArabiaVehicleM2": ("M2 Bradley", "M2 Bradley infantry fighting vehicle"),
    "SaudiArabiaVehicleLAV": ("Tuwaiq-2", "Tuwaiq-2 8x8 armored personnel carrier"),
    "SaudiArabiaVehicleAvenger": ("Avenger", "M1097 Avenger short-range AA"),
    "SaudiArabiaVehiclePatriot": ("Patriot PAC-3", "MIM-104 Patriot PAC-3"),
    "SaudiArabiaVehicleMPQ53": ("AN/MPQ-53", "Patriot AN/MPQ-53 engagement radar"),
    "SaudiArabiaVehicleASTROS": ("HIMARS", "M142 HIMARS rocket launcher"),
    "SaudiArabiaVehicleATACMS": ("ATACMS", "MGM-140 ATACMS ballistic missile TEL"),
    "SaudiArabiaVehicleM109": ("M109A6 Paladin", "M109A6 Paladin self-propelled howitzer"),
    "SaudiArabiaVehicleLAVAT": ("LAV-AT", "LAV-AT TOW anti-tank vehicle"),
    "SaudiArabiaVehicleM88": ("M88 ARV", "M88 armored recovery vehicle"),
    "SaudiArabiaVehiclePatriotBtry": ("THAAD", "Terminal High Altitude Area Defense"),
    # UAE
    "UAETankLeclerc": ("Leclerc UAE", "UAE Leclerc tropical main battle tank"),
    "UAEVehicleBMP3": ("BMP-3", "UAE BMP-3 infantry fighting vehicle"),
    "UAEVehicleNimr": ("Nimr Ajban", "Nimr Ajban scout vehicle"),
    "UAEVehicleRabdan": ("Rabdan", "Rabdan 8x8 infantry fighting vehicle"),
    "UAEVehiclePatria": ("Nimr Hafeet", "Nimr Hafeet armored personnel carrier"),
    "UAEVehiclePantsir": ("Pantsir-S1", "UAE Pantsir-S1 short-range AA"),
    "UAEVehiclePatriot": ("Patriot PAC-3", "UAE MIM-104 Patriot PAC-3"),
    "UAEVehicleRadar": ("AN/MPQ-65", "Patriot AN/MPQ-65 engagement radar"),
    "UAEVehicleHIMARS": ("HIMARS", "UAE M142 HIMARS rocket launcher"),
    "UAEVehicleThunder": ("ATACMS", "MGM-140 ATACMS ballistic missile TEL"),
    "UAEVehicleG6": ("G6 Rhino", "G6 Rhino 155mm self-propelled howitzer"),
    "UAEVehicleBMP3AT": ("BMP-3 Kornet", "BMP-3 with Kornet anti-tank missiles"),
    "UAEVehicleLeclercARV": ("Leclerc ARV", "Leclerc armored recovery vehicle"),
    "UAEVehicleJobaria": ("Jobaria MLS", "Jobaria multiple launch rocket system"),
    # Vietnam
    "VietnamTankT90S": ("T-90S", "Vietnamese T-90S main battle tank"),
    "VietnamTankT54M3": ("T-54M3", "T-54M3 upgraded heavy tank"),
    "VietnamVehicleBRDM": ("BRDM-2", "BRDM-2 armored recon vehicle"),
    "VietnamVehicleBMP1": ("BMP-2", "BMP-2 infantry fighting vehicle"),
    "VietnamVehicleBTR80": ("BTR-80", "BTR-80 armored personnel carrier"),
    "VietnamVehicleShilka": ("ZSU-23-4", "ZSU-23-4 Shilka self-propelled AA"),
    "VietnamVehicleS300": ("S-300PMU1", "S-300PMU1 air-defense system"),
    "VietnamVehicle36D6": ("36D6", "36D6 air-search radar"),
    "VietnamVehicleBM21": ("BM-21 Grad", "BM-21 Grad multiple rocket launcher"),
    "VietnamVehicleScud": ("Scud-B", "Scud-B ballistic missile TEL"),
    "VietnamVehicle2S3": ("2S3 Akatsiya", "2S3 Akatsiya self-propelled howitzer"),
    "VietnamVehicleKonkurs": ("9P148 Konkurs", "9P148 Konkurs anti-tank vehicle"),
    "VietnamVehicleBREM": ("BREM-1", "BREM-1 armored recovery vehicle"),
    "VietnamVehicleBastion": ("K-300P Bastion", "K-300P Bastion coastal missile launcher"),
    # Syria
    "SyriaTankT72": ("T-72", "Syrian T-72 main battle tank"),
    "SyriaTankT62": ("T-62", "Syrian T-62 heavy tank"),
    "SyriaVehicleBRDM": ("BRDM-2", "BRDM-2 armored recon vehicle"),
    "SyriaVehicleBMP1": ("BMP-1", "BMP-1 infantry fighting vehicle"),
    "SyriaVehicleBTR": ("BTR-80", "BTR-80 armored personnel carrier"),
    "SyriaVehicleShilka": ("ZSU-23-4", "ZSU-23-4 Shilka self-propelled AA"),
    "SyriaVehicleBuk": ("Buk-M2", "Buk-M2 medium-range SAM"),
    "SyriaVehicleP18": ("P-18", "P-18 air-search radar"),
    "SyriaVehicleBM21": ("BM-21 Grad", "BM-21 Grad multiple rocket launcher"),
    "SyriaVehicleScud": ("Scud", "Scud ballistic missile TEL"),
    "SyriaVehicle2S1": ("2S1 Gvozdika", "2S1 Gvozdika self-propelled howitzer"),
    "SyriaVehicleKornet": ("9K135 Kornet", "9K135 Kornet anti-tank vehicle"),
    "SyriaVehicleBREM": ("BREM-1", "BREM-1 armored recovery vehicle"),
    "SyriaVehicleTOS1A": ("TOS-1A", "TOS-1A Solntsepek heavy flamethrower"),
    # Libya
    "LibyaTankT72": ("T-72", "Libyan T-72 main battle tank"),
    "LibyaTankT62": ("T-62", "Libyan T-62 heavy tank"),
    "LibyaVehicleBRDM": ("EE-9 Cascavel", "EE-9 Cascavel armored recon vehicle"),
    "LibyaVehicleBMP1": ("BMP-1", "Libyan BMP-1 infantry fighting vehicle"),
    "LibyaVehicleM113": ("M113", "M113 armored personnel carrier"),
    "LibyaVehicleShilka": ("ZSU-23-4", "ZSU-23-4 Shilka self-propelled AA"),
    "LibyaVehicleSA6": ("2K12 Kub", "2K12 Kub / SA-6 air-defense system"),
    "LibyaVehicleRadar": ("P-15", "P-15 air-search radar"),
    "LibyaVehicleBM21": ("BM-21 Grad", "BM-21 Grad multiple rocket launcher"),
    "LibyaVehicleScudB": ("Scud-B", "Scud-B ballistic missile TEL"),
    "LibyaVehicle2S1": ("2S1 Gvozdika", "2S1 Gvozdika self-propelled howitzer"),
    "LibyaVehicleATGM": ("9P122 Malyutka", "9P122 Malyutka anti-tank vehicle"),
    "LibyaVehicleBREM": ("BREM-1", "BREM-1 armored recovery vehicle"),
    "LibyaVehicleScudBtry": ("9K52 Luna-M", "9K52 Luna-M / FROG-7 rocket TEL"),
    # South Africa
    "SouthAfricaTankOlifant": ("Olifant Mk2", "SANDF Olifant Mk2 main battle tank"),
    "SouthAfricaTankOlifant1B": ("Olifant Mk1B", "SANDF Olifant Mk1B heavy tank"),
    "SouthAfricaVehicleRooikat": ("Rooikat", "Rooikat armored recon vehicle"),
    "SouthAfricaVehicleRatel": ("Ratel", "Ratel infantry fighting vehicle"),
    "SouthAfricaVehicleCasspir": ("Casspir", "Casspir armored personnel carrier"),
    "SouthAfricaVehicleYstervark": ("Ystervark", "Ystervark self-propelled AA"),
    "SouthAfricaVehicleCactus": ("Cactus", "Cactus / Crotale air-defense system"),
    "SouthAfricaVehicleThutlwa": ("Thutlwa", "ESR 220 Thutlwa air-defense radar"),
    "SouthAfricaVehicleValkiri": ("Valkiri", "Valkiri multiple rocket launcher"),
    "SouthAfricaVehicleBateleur": ("Bateleur", "Bateleur 127mm multiple rocket launcher"),
    "SouthAfricaVehicleG6": ("G6 Rhino", "G6 Rhino 155mm self-propelled howitzer"),
    "SouthAfricaVehicleZT3": ("Ratel ZT3", "Ratel ZT3 anti-tank vehicle"),
    "SouthAfricaVehicleARV": ("Olifant ARV", "Olifant armored recovery vehicle"),
    "SouthAfricaVehicleRooikat76": ("Rooikat 76", "Rooikat 76mm fire-support vehicle"),
}


def display_of(obj: str, fallback: str = "") -> str:
    hit = NAMES.get(obj)
    return hit[0] if hit else fallback


def tooltip_of(obj: str, fallback: str = "") -> str:
    hit = NAMES.get(obj)
    return hit[1] if hit else fallback
